### PR TITLE
Revert "Added [main] section with gpgcheck to the agent-managed repo …

### PR DESCRIPTION
**Pull request by dowgird**
…file. (#484)"

This reverts commit 5f71066c4908d2dbaf8f172b74d95f2109a1f03e.

That commit caused a regression by breaking Puppet clients, see issues/487

### CODE REVIEW

**Comment by dowgird** [comment]
fixes #487

**Comment by Tioborto** [comment]
@dowgird maybe can you try to generate a name for the repository id? like `google-osconfig-agent-repo`

**Comment by dowgird** [comment]
@Tioborto I'm not sure I understand this request. Do you mean a name for a separate repository?

**Comment by Tioborto** [comment]
@dowgird: thank you for the revert too quickly. 
this line must be unique in all configuration: ```buf.WriteString("[main]\n")```
because yum merge all configuration files in `/etc/yum.conf` and `/etc/yum.repos.d/*`

Example not tested but we don't create any conflict:
```
hostname, err := os.Hostname()
if err != nil {
  fmt.Println(err)
  os.Exit(1)
}
buf.WriteString("[%s-google-agent-repo]\n")
```

**Pull request merged**
